### ISSUE TITLE
在运行test.py 时，snapshot 取值epoch_149.pth，但是epoch_149.pth的key出现错误，这种情况如何解决，或者需要跑完train.py得到模型参数吗？

### ISSUE THREAD

**Issue by kebai633932** [SUN-1024/DA-TransUnet#3]
代码   snapshot = os.path.join(snapshot_path, 'best_model.pth')
           if not os.path.exists(snapshot): snapshot = snapshot.replace('best_model', 'epoch_'+str(args.max_epochs-1))
报错：C:\ProgramData\anaconda3\python.exe C:\Users\86133\Desktop\project_TransUNet\TransUNet\test.py 
../model/TU_Synapse224/TU_pretrain_R50-ViT-B_16_skip3_epo150_bs24_224\epoch_149.pth
Traceback (most recent call last):
  File "C:\Users\86133\Desktop\project_TransUNet\TransUNet\test.py", line 139, in <module>
    net.load_state_dict(torch.load(snapshot))
  File "C:\Users\86133\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
	Missing key(s) in state_dict: "transformer.embeddings.hybrid_model.body.block1/.unit1/.gn1.weight", "
	Unexpected key(s) in state_dict: "transformer.embeddings.DAblock1.conv5a.0.weight", 

进程已结束，退出代码为 1
![epoch149](https://github.com/SUN-1024/DA-TransUnet/assets/122462462/63750df2-21cd-4435-a1f7-71a42d11030f)

**Comment by yizhipan** [comment]
https://blog.csdn.net/m0_69607904/article/details/135243311?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22135243311%22%2C%22source%22%3A%22m0_69607904%22%7D

变更代码会导致 我给的.pth文件错误，你重新自己跑试试看

**Comment by LiuYM00** [comment]
您好 我使用了预训练结果，然后跑了train.py文件 ，在测试test.py文件时  出现了通道数不匹配问题  这是什么原因导致的  同时 还想问一下 可以不使用预训练结果 直接训练吗  麻烦您回复一下 谢谢

**Comment by kebai633932** [comment]
可能是你的文件地址读取的不是你训练后的，可能是这样？
